Fix a possible XP multiplication exploit
bl4ckscor3/XP-Tome pull request #15
Opened 2022-02-14 03:50 UTC by TaitoMagatsu91

Some mods allow for stacking of usually unstackable items such as full XP books.

If using stacked XP books while not sneaking, the user will only empty one book but will gain the XP of the entire stack of XP books. Such behavior is exploitable in mod packs that combine the XP-Tome mod with mods that allow stacking of usually unstackable items.

This change fixes the possibility of an exploit, by cancelling the interaction with the book held if the user has any amount of books in their hand other than just the one.

---

## Context

Hey this mod is pretty sweet. Thank you for making it!

I'm here because while playing a 1.12 modpack that includes the Charm mod, I found it was possible to use its bookshelf chests, which only accept book-type items, to stack full (as well as empty) XP tomes. It was awesome. Then a friend discovered that you could actually right click on a stack to extract the full XP stored in all of its books, while only emptying one of them. This was exploitable to obtain infinite XP.

I tried to make a patch as non-invasive as possible, such that you could check it with the least amount of effort possible.

Thanks for reading so far, and I hope you consider accepting this PR <3

2022-02-14 08:23 UTC, bl4ckscor3 requested changes
Arguably, nothing should allow stacking of unstackable items, because unstackable items are made like that for a reason. But this fix is simple enough, so it works for me. However, this code will not compile, since the `stackSize` field is private and thus not accessible.

2022-02-15 07:50 UTC, TaitoMagatsu91 reviewed
Ah, you're completely correct. I was working with the Forge 12 docs. Now that I look at Forge 14's docs, this field became private and it seems to me like `getCount()` is the intended alternative to it. The docs themselves don't say much, so I'm still digging to see if I can find a description of the method itself.

2022-02-15 07:54 UTC, TaitoMagatsu91 commented
Okay, after digging some more, it seems like `getCount()` is precisely the right method to be calling :+1: :3

2022-02-15 09:06 UTC, bl4ckscor3 approved these changes

2022-02-15 09:06 UTC, merged